version: '3'
services:
  acmesky-frontend:
    container_name: acmesky-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - acmesky

networks:
  acmesky:
    external: true